name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File - 23f3003463@ds.study.iitm.ac.in
        run: |
          echo "$(date)" > daily-log.txt  # Overwrites the file

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily-log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push origin main
